import type { MaterialRequestItemColumnId } from "@/app/src/types/modules/inventory/material-request/MaterialRequestItemEntryTypes";

export const DefaultItemColumnOrder = [
	"itemCode",
	"barcode",
	"itemName",
	"requestQuantity",
	"stockQuantity",
	"uom",
	"manufacturingDate",
	"expiryDate",
	"lotNo",
	"serialNumber",
	"costCenter",
	"color",
	"brand",
	"size",
	"model",
	"description",
	"category",
	"batchNo",
	"warehouse",
	"location",
	"unitCost",
	"unitPrice",
	"remarks",
] satisfies MaterialRequestItemColumnId[];

export const DefaultVisibleItemColumnOrder: MaterialRequestItemColumnId[] = [
	"itemCode",
	"barcode",
	"itemName",
	"requestQuantity",
	"stockQuantity",
	"uom",
	"manufacturingDate",
	"expiryDate",
	"lotNo",
	"serialNumber",
	"costCenter",
	"color",
	"brand",
	"size",
	"model",
];

export const LegacyDefaultItemColumnOrder = [
	"itemCode",
	"barcode",
	"itemName",
	"category",
	"uom",
	"requestQuantity",
	"stockQuantity",
	"lotNo",
	"remarks",
] satisfies MaterialRequestItemColumnId[];

export const DefaultRequiredItemColumnOrder = [
	"itemCode",
	"itemName",
	"uom",
	"requestQuantity",
] satisfies MaterialRequestItemColumnId[];

export const DefaultRequiredItemColumnIds = new Set<MaterialRequestItemColumnId>(
	DefaultRequiredItemColumnOrder,
);

export const ProtectedItemColumnIds = DefaultRequiredItemColumnIds;

export const DefaultItemColumnLabels: Record<MaterialRequestItemColumnId, string> = {
	batchNo: "Batch No.",
	barcode: "Barcode",
	brand: "Brand",
	category: "Item Category",
	color: "Color",
	costCenter: "Res Center",
	description: "Description",
	expiryDate: "Expiration Date",
	itemCode: "Item Code *",
	itemName: "Item Name *",
	lotNo: "Lot No.",
	location: "Location",
	manufacturingDate: "Mfg Date",
	model: "Model",
	remarks: "Remarks",
	requestQuantity: "MR Qty *",
	serialNumber: "Serial No.",
	size: "Size",
	stockQuantity: "Stock Qty",
	unitCost: "Unit Cost",
	unitPrice: "Unit Price",
	uom: "UOM *",
	warehouse: "Warehouse",
};

export const DefaultItemColumnWidths: Record<MaterialRequestItemColumnId, number> = {
	batchNo: 150,
	barcode: 90,
	brand: 90,
	category: 190,
	color: 90,
	costCenter: 105,
	description: 240,
	expiryDate: 120,
	itemCode: 110,
	itemName: 220,
	lotNo: 105,
	location: 170,
	manufacturingDate: 115,
	model: 95,
	remarks: 260,
	requestQuantity: 95,
	serialNumber: 105,
	size: 85,
	stockQuantity: 95,
	unitCost: 150,
	unitPrice: 150,
	uom: 85,
	warehouse: 170,
};

export const DefaultImportIndexes: Partial<Record<MaterialRequestItemColumnId, number>> = {
	batchNo: 7,
	barcode: 1,
	brand: 19,
	category: 4,
	color: 18,
	costCenter: 10,
	description: 3,
	expiryDate: 16,
	itemCode: 0,
	itemName: 2,
	lotNo: 15,
	location: 9,
	manufacturingDate: 17,
	model: 21,
	remarks: 22,
	requestQuantity: 11,
	serialNumber: 6,
	size: 20,
	stockQuantity: 12,
	unitCost: 13,
	unitPrice: 14,
	uom: 5,
	warehouse: 8,
};

export let materialRequestTextMeasureContext:
	| CanvasRenderingContext2D
	| null
	| undefined;

export const MaterialRequestImportTemplateRows = [
	[
		"ITM-0001",
		"480000000001",
		"Portland Cement",
		"Portland cement bags",
		"Construction Materials",
		"Bag",
		"SN-0001",
		"BATCH-2406",
		"Main Warehouse",
		"Aisle 1",
		"OPS",
		"120",
		"320",
		"245.5",
		"275",
		"LOT-CEM-2405",
		"2026-12-31",
		"2024-01-15",
		"Gray",
		"BuildPro",
		"40kg",
		"CP-40",
		"Priority site requirement",
	],
	[
		"ITM-0002",
		"480000000002",
		"Steel Bar 10mm",
		"Deformed steel bar",
		"Construction Materials",
		"Pcs",
		"SN-0002",
		"BATCH-2405",
		"Site Warehouse 1",
		"Rack B",
		"STR",
		"75",
		"210",
		"140",
		"165",
		"LOT-STL-2405",
		"2028-01-31",
		"2024-02-20",
		"Silver",
		"SteelMax",
		"10mm",
		"SB-10",
		"For structural works",
	],
];

export const ImportPageSize = 8;

