import { formatTransactionNumber } from "@/app/src/services/modules/system-administration/transaction-number-setup/TransactionNumberGenerationService";
import type { TransactionNumberSetupRecord } from "@/app/src/types/modules/system-administration/transaction-number-setup/TransactionNumberSetupTypes";

export function getPartyManagementNumberSetup(
	setups: TransactionNumberSetupRecord[],
	branchUnitId?: number | null,
) {
	return setups.find(
		(setup) =>
			setup.moduleCode === "PM" &&
			setup.status === "Active" &&
			(setup.scope !== "branch" ||
				!branchUnitId ||
				setup.branchIds.includes(String(branchUnitId))),
	);
}

export function isPartyCodeAutoGenerated(
	setup: TransactionNumberSetupRecord | undefined,
) {
	return setup?.inputMode === "Auto";
}

export function getNextPartyCodePreview(
	setup: TransactionNumberSetupRecord | undefined,
) {
	return setup && isPartyCodeAutoGenerated(setup)
		? formatTransactionNumber(setup)
		: "";
}
