"use client";

import { useState, type ChangeEvent, type FormEvent } from "react";
import { useParams, usePathname, useRouter } from "next/navigation";
import toast from "react-hot-toast";
import { WarehouseHref } from "@/app/src/constants/modules/maintenance/warehouses/WarehouseConstants";
import { WarehouseInitialFormValues, createWarehouseFormValues, updateWarehouseRecord } from "@/app/src/data/modules/maintenance/warehouses/WarehouseData";
import { useTransactionNumberSetupStore } from "@/app/src/hooks/modules/system-administration/transaction-number-setup/useTransactionNumberSetup";
import { useAppStore } from "@/app/src/hooks/shared/app/useAppStore";
import {
  getNextWarehouseCodePreview,
  getWarehouseNumberSetup,
  isWarehouseCodeAutoGenerated,
} from "@/app/src/services/modules/maintenance/warehouses/WarehouseNumbering";
import type {
  WarehouseActionMode,
  WarehouseRecord,
  WarehouseFormErrors,
  WarehouseFormValues,
} from "@/app/src/types/modules/maintenance/warehouses/WarehouseTypes";
import { validateWarehouseForm } from "@/app/src/validations/modules/maintenance/warehouses/WarehouseValidation";
import { useWarehousesStore } from "@/app/src/hooks/modules/maintenance/warehouses/useWarehouses";

type WarehouseFormPageOptions = {
  existingWarehouse?: WarehouseRecord;
  mode?: WarehouseActionMode;
  onSaved?: () => void;
};

export function useWarehouseFormPage(options: WarehouseFormPageOptions = {}) {
  const params = useParams<{ recordId?: string }>();
  const pathname = usePathname();
  const router = useRouter();
  const { addWarehouse, isMutating, setWarehouseStatus, updateWarehouse, warehouses } = useWarehousesStore();
  const activeBranchId = useAppStore((state) => state.activeBranchId);
  const transactionNumberSetup = useTransactionNumberSetupStore();
  const mode = options.mode ?? getActionMode(pathname);
  const existingWarehouse = options.existingWarehouse ?? warehouses.find((warehouse) => warehouse.id === params.recordId);
  const isReadonly = mode === "view";
  const [values, setValues] = useState<WarehouseFormValues>(() =>
    existingWarehouse ? createWarehouseFormValues(existingWarehouse) : WarehouseInitialFormValues,
  );
  const [errors, setErrors] = useState<WarehouseFormErrors>({});
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const warehouseNumberSetup = getWarehouseNumberSetup(transactionNumberSetup.setups, activeBranchId);
  const isWarehouseCodeReadonly = mode === "add" && isWarehouseCodeAutoGenerated(warehouseNumberSetup);
  const warehouseCodePreview = getNextWarehouseCodePreview(warehouseNumberSetup);
  const effectiveValues = isWarehouseCodeReadonly && warehouseCodePreview ? { ...values, code: warehouseCodePreview } : values;

  function updateField(field: keyof WarehouseFormValues, value: WarehouseFormValues[keyof WarehouseFormValues]) {
    if (isReadonly) {
      return;
    }

    setValues((current) => {
      return { ...current, [field]: value };
    });
    setErrors((current) => ({
      ...current,
      [field]: undefined,
    }));
  }

  function handleInputChange(event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) {
    if (event.target.name === "code" && isWarehouseCodeReadonly) {
      return;
    }

    updateField(event.target.name as keyof WarehouseFormValues, event.target.value);
  }

  function updateAvailabilityMode(branchAvailabilityMode: WarehouseFormValues["branchAvailabilityMode"]) {
    if (isReadonly) {
      return;
    }

    setValues((current) => ({
      ...current,
      branchAvailabilityMode,
      branchUnitIds: branchAvailabilityMode === "All Branches" ? [] : current.branchUnitIds,
      availableBranches: branchAvailabilityMode === "All Branches" ? [] : current.availableBranches,
    }));
    setErrors((current) => ({
      ...current,
      availableBranches: undefined,
      branchAvailabilityMode: undefined,
      branchUnitIds: undefined,
    }));
  }

  function toggleBranch(branchId: string) {
    if (isReadonly) {
      return;
    }

    const branch = transactionNumberSetup.branchOptions.find((branchOption) => branchOption.id === branchId);

    setValues((current) => {
      const isSelected = current.branchUnitIds.includes(branchId);
      const branchUnitIds = isSelected ? current.branchUnitIds.filter((currentId) => currentId !== branchId) : [...current.branchUnitIds, branchId];
      const availableBranches = transactionNumberSetup.branchOptions
        .filter((branchOption) => branchUnitIds.includes(branchOption.id))
        .map((branchOption) => branchOption.name);

      return {
        ...current,
        branchUnitIds,
        availableBranches: availableBranches.length > 0 ? availableBranches : branch && !isSelected ? [branch.name] : [],
      };
    });
    setErrors((current) => ({
      ...current,
      availableBranches: undefined,
      branchUnitIds: undefined,
    }));
  }

  function setBranchSelection(branchUnitIds: string[]) {
    if (isReadonly) {
      return;
    }

    const uniqueBranchUnitIds = Array.from(new Set(branchUnitIds));
    const availableBranches = transactionNumberSetup.branchOptions
      .filter((branchOption) => uniqueBranchUnitIds.includes(branchOption.id))
      .map((branchOption) => branchOption.name);

    setValues((current) => ({
      ...current,
      branchUnitIds: uniqueBranchUnitIds,
      availableBranches,
    }));
    setErrors((current) => ({
      ...current,
      availableBranches: undefined,
      branchUnitIds: undefined,
    }));
  }

  function validateBeforeSubmit() {
    const nextErrors = validateWarehouseForm(effectiveValues, {
      isWarehouseCodeRequired: !isWarehouseCodeReadonly,
    });

    if (Object.keys(nextErrors).length > 0) {
      setErrors(nextErrors);
      toast.error("Please fix the highlighted warehouse fields.");
      return false;
    }

    return true;
  }

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (!validateBeforeSubmit()) {
      return;
    }

    if (mode === "edit" && existingWarehouse) {
      void updateWarehouse(updateWarehouseRecord(existingWarehouse, effectiveValues))
        .then(() => {
          options.onSaved?.();
          if (!options.onSaved) {
            router.push(WarehouseHref);
          }
        })
        .catch(() => undefined);
      return;
    }

    if (mode === "edit") {
      toast.error("Could not find the warehouse to update.");
      return;
    }

    void addWarehouse(effectiveValues)
      .then(() => {
        options.onSaved?.();
        if (!options.onSaved) router.push(WarehouseHref);
      })
      .catch(() => undefined);
  }

  function handleConfirmDelete() {
    if (!existingWarehouse) {
      toast.error("Could not find the warehouse to delete.");
      return;
    }

    void setWarehouseStatus(existingWarehouse.id, "Inactive")
      .then(() => {
        setIsDeleteDialogOpen(false);
        router.push(WarehouseHref);
      })
      .catch(() => undefined);
  }

  return {
    errors,
    existingWarehouse,
    handleConfirmDelete,
    handleInputChange,
		handleStatusChange: (status: WarehouseFormValues["status"]) =>
			updateField("status", status),
    handleSubmit,
    isDeleteDialogOpen,
    isMutating,
    isReadonly,
    isWarehouseCodeReadonly,
    mode,
    needsRecord: mode === "edit" || mode === "view",
    setIsDeleteDialogOpen,
    branchOptions: transactionNumberSetup.branchOptions,
    setBranchSelection,
    toggleBranch,
    updateAvailabilityMode,
    validateBeforeSubmit,
    values: effectiveValues,
  };
}

function getActionMode(pathname: string): WarehouseActionMode {
  if (pathname.includes("/view/")) {
    return "view";
  }

  if (pathname.includes("/edit/")) {
    return "edit";
  }

  return "add";
}
