"use client";

import {
	useMemo,
	useState,
	type ChangeEvent,
	type FormEvent,
} from "react";
import {
	PartyManagementDrawerPrimaryActionClassName,
	PartyManagementDrawerFormId,
	PartyManagementDrawerSecondaryActionClassName,
	PartyTypeOptions,
} from "@/app/src/constants/modules/maintenance/party-management/PartyManagementConstants";
import {
	PartyInformationInitialFormValues,
	applyPartyDefaultAccountingAccounts,
	clearAddressRolesForPartyTypes,
	createPartyInformationRecord,
	isKnownPartyType,
	normalizePartyTypesForClassification,
} from "@/app/src/data/modules/maintenance/party-management/PartyManagementData";
import { FormatPhilippineContactNumber } from "@/app/src/data/shared/contact/ContactData";
import { FormatTinNumber } from "@/app/src/data/shared/tax/TaxData";
import { useAddressOptions } from "@/app/src/hooks/shared/address/useAddressOptions";
import { useTermDropdownOptions } from "@/app/src/hooks/modules/maintenance/term-management/useTermDropdownOptions";
import { usePartyManagementAccountOptions } from "@/app/src/hooks/modules/maintenance/party-management/usePartyManagementAccountOptions";
import { useTransactionNumberSetupStore } from "@/app/src/hooks/modules/system-administration/transaction-number-setup/useTransactionNumberSetup";
import { useAppStore } from "@/app/src/hooks/shared/app/useAppStore";
import { usePartyAtcCodeOptions } from "@/app/src/hooks/shared/tax/useAlphanumericTaxCodeOptions";
import {
	getNextPartyCodePreview,
	getPartyManagementNumberSetup,
	isPartyCodeAutoGenerated,
} from "@/app/src/services/modules/maintenance/party-management/PartyManagementNumbering";
import type {
	PartyAddress,
	PartyInformationFormErrors,
	PartyInformationFormValues,
	PartyInformationRecord,
	PartyManagementDrawerProps,
	PartyProvinceOption,
} from "@/app/src/types/modules/maintenance/party-management/PartyManagementTypes";
import { validatePartyInformationForm } from "@/app/src/validations/modules/maintenance/party-management/PartyManagementValidation";
import { ModuleDrawer } from "@/app/src/ui/shared/module/ModuleDrawer";
import { PartyInformationDetailsFields } from "@/app/src/ui/modules/maintenance/party-management/PartyInformationDetailsFields";
import type {
	AddressAutocompleteDetails,
	AddressAutocompleteItem,
} from "@/app/src/types/shared/address/AddressTypes";
import type { AppAdvancedDropdownOption } from "@/app/src/ui/shared/advanced-dropdown/AppAdvancedDropdown";

export function PartyManagementDrawer({
	description = "Create a party record from the party-management fields, then use it on this transaction.",
	isOpen,
	isPending,
	onAddRecord,
	onClose,
	onCreateParty,
	records,
	title = "Add Party Code",
}: PartyManagementDrawerProps) {
	const [values, setValues] = useState<PartyInformationFormValues>(() =>
		createPartyDrawerInitialValues(records),
	);
	const activeBranchId = useAppStore((state) => state.activeBranchId);
	const partyAccountOptions = usePartyManagementAccountOptions();
	const termDropdown = useTermDropdownOptions();
	const transactionNumberSetup = useTransactionNumberSetupStore();
	const [errors, setErrors] = useState<PartyInformationFormErrors>({});
	const activeAddress =
		values.addresses.find((address) => address.id === values.activeAddressId) ??
		values.addresses[0] ??
		values.address;
	const addressOptions = useAddressOptions({
		barangayCode: activeAddress.barangayCode,
		barangayName: activeAddress.barangay,
		cityMunicipalityCode: activeAddress.cityMunicipalityCode,
		cityMunicipalityName: activeAddress.cityMunicipality,
		provinceCode: activeAddress.provinceCode,
		provinceName: activeAddress.province,
		regionCode: activeAddress.regionCode,
		regionName: activeAddress.region,
	});
	const isClassificationSelected = Boolean(values.classification);
	const canSave = isClassificationSelected && values.partyTypes.length > 0;
	const partyNumberSetup = useMemo(
		() =>
			getPartyManagementNumberSetup(
				transactionNumberSetup.setups,
				activeBranchId,
			),
		[activeBranchId, transactionNumberSetup.setups],
	);
	const isAutoPartyCode = isPartyCodeAutoGenerated(partyNumberSetup);
	const partyCodePreview = getNextPartyCodePreview(partyNumberSetup);
	const accountingValues = useMemo(
		() =>
			applyPartyDefaultAccountingAccounts(
				values,
				values.partyTypes,
				partyAccountOptions.defaultAccounts,
			),
		[partyAccountOptions.defaultAccounts, values],
	);
	const effectiveValues = useMemo(
		() =>
			isAutoPartyCode && partyCodePreview
				? { ...accountingValues, partyCodeNo: partyCodePreview }
				: accountingValues,
		[accountingValues, isAutoPartyCode, partyCodePreview],
	);
	const atcDropdown = usePartyAtcCodeOptions(values.classification);

	function updateField<TKey extends keyof PartyInformationFormValues>(
		field: TKey,
		value: PartyInformationFormValues[TKey],
	) {
		setValues((current) => {
			if (field === "classification") {
				const classification =
					value as PartyInformationFormValues["classification"];
				const partyTypes = normalizePartyTypesForClassification(
					current.partyTypes,
					classification,
				);
				const accountingAccounts = applyPartyDefaultAccountingAccounts(
					current,
					partyTypes,
					partyAccountOptions.defaultAccounts,
				);

				return {
					...current,
					classification,
					partyTypes,
					partyName: "",
					tradeName: "",
					firstName: "",
					middleName: "",
					lastName: "",
					suffixName: "",
					atcCode: "",
					addresses: clearAddressRolesForPartyTypes(
						current.addresses,
						partyTypes,
						classification,
					),
					defaultReceivableAccount: accountingAccounts.defaultReceivableAccount,
					customerAdvanceAccount: accountingAccounts.customerAdvanceAccount,
					defaultPayableAccount: accountingAccounts.defaultPayableAccount,
					vendorAdvanceAccount: accountingAccounts.vendorAdvanceAccount,
					employeeAdvanceAccount: accountingAccounts.employeeAdvanceAccount,
					employeePayableAccount: accountingAccounts.employeePayableAccount,
				};
			}

			return {
				...current,
				[field]: value,
			};
		});
		setErrors((current) => ({ ...current, [field]: undefined }));
	}

	function updateAddressField(
		field: keyof PartyAddress,
		value: string,
		addressId?: string,
	) {
		if (!isClassificationSelected) {
			return;
		}

		setValues((current) => ({
			...current,
			addresses: current.addresses.map((address) =>
				address.id === (addressId ?? current.activeAddressId)
					? { ...address, [field]: value }
					: address,
			),
		}));
		if (field === "addressLine1" || field === "addressLine2") {
			setErrors((current) => ({ ...current, [field]: undefined }));
		}
	}

	function handleInputChange(
		event: ChangeEvent<HTMLInputElement | HTMLSelectElement>,
	) {
		const field = event.target.name as keyof PartyInformationFormValues;
		const value =
			field === "tin"
				? FormatTinNumber(event.target.value)
				: field === "contactNo"
					? FormatPhilippineContactNumber(event.target.value)
					: event.target.value;

		updateField(field, value as never);
	}

	function handleAddressInputChange(event: ChangeEvent<HTMLInputElement>) {
		updateAddressField(
			event.target.name as keyof PartyAddress,
			event.target.value,
			event.currentTarget.dataset.addressId,
		);
	}

	function handlePartyTypesChange(value: string | string[]) {
		if (!isClassificationSelected) {
			return;
		}

		const selectedValues = Array.isArray(value) ? value : [value];
		const partyTypes = selectedValues.filter(isKnownPartyType);

		setValues((current) => {
			const accountingAccounts = applyPartyDefaultAccountingAccounts(
				current,
				partyTypes,
				partyAccountOptions.defaultAccounts,
			);

			return {
				...current,
				partyTypes,
				addresses: clearAddressRolesForPartyTypes(
					current.addresses,
					partyTypes,
					current.classification,
				),
				defaultReceivableAccount: accountingAccounts.defaultReceivableAccount,
				customerAdvanceAccount: accountingAccounts.customerAdvanceAccount,
				defaultPayableAccount: accountingAccounts.defaultPayableAccount,
				vendorAdvanceAccount: accountingAccounts.vendorAdvanceAccount,
				employeeAdvanceAccount: accountingAccounts.employeeAdvanceAccount,
				employeePayableAccount: accountingAccounts.employeePayableAccount,
			};
		});
		setErrors((current) => ({ ...current, partyTypes: undefined }));
	}

	function selectAtcCode(value: string | string[]) {
		if (!isClassificationSelected) {
			return;
		}

		setValues((current) => ({
			...current,
			atcCode: getSingleSelectedValue(value),
		}));
		setErrors((current) => ({ ...current, atcCode: undefined }));
	}

	function selectProvince(
		value: string | string[],
		addressId?: string,
		selectedOption?: PartyProvinceOption,
	) {
		if (!isClassificationSelected) {
			return;
		}

		const code = getSingleSelectedValue(value);
		const option = selectedOption ?? addressOptions.provinceOptions.find(
			(province) => province.value === code,
		);

		setValues((current) => ({
			...current,
			addresses: current.addresses.map((address) =>
				address.id === (addressId ?? current.activeAddressId)
					? {
						...address,
						barangay: "",
						barangayCode: "",
						cityMunicipality: "",
						cityMunicipalityCode: "",
						province: option?.name ?? "",
						provinceCode: code,
						region: option?.regionName ?? "",
						regionCode: option?.regionCode ?? "",
					}
					: address,
			),
		}));
		clearAddressErrors([
			"regionCode",
			"provinceCode",
			"cityMunicipalityCode",
			"barangayCode",
		]);
	}

	function selectAutocompleteAddress(
		address: AddressAutocompleteItem,
		details?: AddressAutocompleteDetails,
		addressId?: string,
	) {
		if (!isClassificationSelected) {
			return;
		}

		setValues((current) => ({
			...current,
			addresses: current.addresses.map((currentAddress) =>
				currentAddress.id === (addressId ?? current.activeAddressId)
					? {
						...currentAddress,
						addressLine1:
							details?.addressLine1 ?? currentAddress.addressLine1,
						addressLine2:
							details?.addressLine2 ?? currentAddress.addressLine2,
						barangay: address.barangay.name,
						barangayCode: address.barangay.code,
						cityMunicipality: address.cityMunicipality.name,
						cityMunicipalityCode: address.cityMunicipality.code,
						province: address.province.name,
						provinceCode: address.province.code,
						region: address.region.name,
						regionCode: address.region.code,
					}
					: currentAddress,
			),
		}));
		clearAddressErrors([
			"addressLine1",
			"addressLine2",
			"regionCode",
			"provinceCode",
			"cityMunicipalityCode",
			"barangayCode",
		]);
	}

	function syncAutocompleteAddressDetails(
		details: AddressAutocompleteDetails,
		addressId?: string,
	) {
		if (!isClassificationSelected) {
			return;
		}

		setValues((current) => ({
			...current,
			addresses: current.addresses.map((currentAddress) =>
				currentAddress.id === (addressId ?? current.activeAddressId)
					? {
						...currentAddress,
						addressLine1: details.addressLine1 ?? currentAddress.addressLine1,
						addressLine2: details.addressLine2 ?? currentAddress.addressLine2,
					}
					: currentAddress,
			),
		}));
		clearAddressErrors(["addressLine1", "addressLine2"]);
	}

	function selectCityMunicipality(
		value: string | string[],
		addressId?: string,
		selectedOption?: AppAdvancedDropdownOption,
	) {
		if (!isClassificationSelected) {
			return;
		}

		const code = getSingleSelectedValue(value);
		const option = selectedOption ?? addressOptions.cityMunicipalityOptions.find(
			(cityMunicipality) => cityMunicipality.value === code,
		);

		setValues((current) => ({
			...current,
			addresses: current.addresses.map((address) =>
				address.id === (addressId ?? current.activeAddressId)
					? {
						...address,
						barangay: "",
						barangayCode: "",
						cityMunicipality: option?.name ?? "",
						cityMunicipalityCode: code,
					}
					: address,
			),
		}));
		clearAddressErrors(["cityMunicipalityCode", "barangayCode"]);
	}

	function selectBarangay(
		value: string | string[],
		addressId?: string,
		selectedOption?: AppAdvancedDropdownOption,
	) {
		if (!isClassificationSelected) {
			return;
		}

		const code = getSingleSelectedValue(value);
		const option = selectedOption ?? addressOptions.barangayOptions.find(
			(barangay) => barangay.value === code,
		);

		setValues((current) => ({
			...current,
			addresses: current.addresses.map((address) =>
				address.id === (addressId ?? current.activeAddressId)
					? {
						...address,
						barangay: option?.name ?? "",
						barangayCode: code,
					}
					: address,
			),
		}));
		clearAddressErrors(["barangayCode"]);
	}

	function clearAddressErrors(fields: (keyof PartyInformationFormErrors)[]) {
		setErrors((current) => {
			const nextErrors = { ...current };

			for (const field of fields) {
				nextErrors[field] = undefined;
			}

			return nextErrors;
		});
	}

	function selectTerm(value: string | string[]) {
		const termId = getSingleSelectedValue(value);
		const term = termDropdown.terms.find((currentTerm) => currentTerm.id === termId);

		setValues((current) => ({
			...current,
			termId,
			termName: term?.name ?? "",
		}));
	}

	function handleSubmit(event?: FormEvent<HTMLFormElement>) {
		event?.preventDefault();

		const nextErrors = validatePartyInformationForm(effectiveValues);

		if (Object.keys(nextErrors).length > 0) {
			setErrors(nextErrors);
			return;
		}

		const record = createPartyInformationRecord(effectiveValues);

		onAddRecord(record);
		onCreateParty(record);
		onClose();
	}

	return (
		<ModuleDrawer
			description={description}
			footer={
				<div className="flex flex-wrap justify-end gap-2">
					<button
						type="button"
						onClick={onClose}
						className={PartyManagementDrawerSecondaryActionClassName}
					>
						Cancel
					</button>
					<button
						type="button"
						onClick={() => handleSubmit()}
						disabled={isPending || !canSave}
						className={PartyManagementDrawerPrimaryActionClassName}
					>
						Save Party
					</button>
				</div>
			}
			isOpen={isOpen}
			maxWidthClassName="max-w-5xl"
			onClose={onClose}
			title={title}
		>
			<div id={PartyManagementDrawerFormId} className="px-6 py-5">
				<PartyInformationDetailsFields
					accountOptions={partyAccountOptions.accountOptions}
					atcOptions={atcDropdown.options}
					errors={errors}
					isClassificationSelected={isClassificationSelected}
					isPartyCodeReadonly={isAutoPartyCode}
					isReadonly={false}
					partyTypeOptions={PartyTypeOptions}
					termOptions={termDropdown.options}
					values={effectiveValues}
					onAddressInputChange={handleAddressInputChange}
					onInputChange={handleInputChange}
					onPartyTypesChange={handlePartyTypesChange}
					onSelectBarangay={selectBarangay}
					onSelectAtcCode={selectAtcCode}
					onSelectAutocompleteAddress={selectAutocompleteAddress}
					onSyncAutocompleteAddressDetails={syncAutocompleteAddressDetails}
					onSelectCityMunicipality={selectCityMunicipality}
					onSelectProvince={selectProvince}
					onSelectTerm={selectTerm}
					onUpdateField={updateField}
				/>
			</div>
		</ModuleDrawer>
	);
}

function createPartyDrawerInitialValues(
	records: PartyInformationRecord[],
): PartyInformationFormValues {
	return {
		...PartyInformationInitialFormValues,
		partyCodeNo: createNextPartyCode(records),
		status: "Active",
	};
}

function createNextPartyCode(records: PartyInformationRecord[]) {
	const nextNumber =
		records.reduce((highest, record) => {
			const match = record.partyCodeNo.match(/(\d+)$/);
			const number = match ? Number.parseInt(match[1], 10) : Number.NaN;

			return Number.isFinite(number) ? Math.max(highest, number) : highest;
		}, 0) + 1;

	return `PTY-${nextNumber.toString().padStart(4, "0")}`;
}

function getSingleSelectedValue(value: string | string[]) {
	return Array.isArray(value) ? (value[0] ?? "") : value;
}

