"use client";

import { useMemo, useState, type ChangeEvent, type FormEvent } from "react";
import toast from "react-hot-toast";
import {
  PartyManagementDrawerPrimaryActionClassName,
  PartyManagementDrawerFormId,
  PartyManagementDrawerSecondaryActionClassName,
  PartyAccountingAccountFieldLabels,
  PartyDefaultNationality,
  PartyTypeOptions,
} from "@/app/src/constants/modules/party-management/PartyManagementConstants";
import {
  PartyInformationInitialFormValues,
  applyPartyDefaultAccountingAccounts,
  clearAddressRolesForPartyTypes,
  createPartyInformationRecord,
  hasPersonalInformationPartyType,
  isKnownPartyType,
  normalizePartyTypesForClassification,
} from "@/app/src/data/modules/party-management/PartyManagementData";
import { FormatPhilippineContactNumber } from "@/app/src/data/shared/contact/ContactData";
import { FormatTinNumber } from "@/app/src/data/shared/tax/TaxData";
import { useAddressOptions } from "@/app/src/hooks/shared/address/useAddressOptions";
import { useTermDropdownOptions } from "@/app/src/hooks/modules/financial-maintenance/term-management/useTermDropdownOptions";
import { usePartyManagementAccountOptions } from "@/app/src/hooks/modules/party-management/usePartyManagementAccountOptions";
import { useChartsOfAccounts } from "@/app/src/hooks/modules/financial-maintenance/charts-of-accounts/useChartsOfAccounts";
import { useTransactionNumberSetupStore } from "@/app/src/hooks/modules/system-administration/transaction-number-setup/useTransactionNumberSetup";
import { useAppStore } from "@/app/src/hooks/shared/app/useAppStore";
import { usePartyAtcCodeOptions } from "@/app/src/hooks/shared/tax/useAlphanumericTaxCodeOptions";
import {
  getNextPartyCodePreview,
  getPartyManagementNumberSetup,
  isPartyCodeAutoGenerated,
} from "@/app/src/services/modules/party-management/PartyManagementNumbering";
import type { ChartAccount } from "@/app/src/types/modules/financial-maintenance/charts-of-accounts/ChartsOfAccountsTypes";
import type {
  PartyAddress,
  PartyAccountingAccountField,
  PartyInformationFormErrors,
  PartyInformationFormValues,
  PartyInformationRecord,
  PartyManagementDrawerProps,
  PartyProvinceOption,
} from "@/app/src/types/modules/party-management/PartyManagementTypes";
import {
  PartyInformationRequiredFieldsToastMessage,
  validatePartyInformationForm,
} from "@/app/src/validations/modules/party-management/PartyManagementValidation";
import { AppDialog } from "@/app/src/ui/shared/app/AppDialog";
import { ModuleDrawer } from "@/app/src/ui/shared/module/ModuleDrawer";
import { ModuleSavingLabel } from "@/app/src/ui/shared/module/ModuleDrawer";
import { PartyInformationDetailsFields } from "@/app/src/ui/modules/party-management/PartyInformationDetailsFields";
import { ChartAccountQuickAddDialog } from "@/app/src/ui/modules/financial-maintenance/charts-of-accounts/ChartAccountQuickAddDialog";
import { TermManagementQuickAddDialog } from "@/app/src/ui/modules/financial-maintenance/term-management/TermManagementQuickAddDialog";
import { todayDateValue } from "@/app/src/utils/date.util";
import type {
  AddressAutocompleteDetails,
  AddressAutocompleteItem,
} from "@/app/src/types/shared/address/AddressTypes";
import type { AppAdvancedDropdownOption } from "@/app/src/ui/shared/advanced-dropdown/AppAdvancedDropdown";

export function PartyManagementDrawer({
  description = "Create a party record from the party-management fields, then use it on this transaction.",
  isOpen,
  isPending,
  onAddRecord,
  onClose,
  onCreateParty,
  records,
  title = "Add Party Code",
}: PartyManagementDrawerProps) {
  const [values, setValues] = useState<PartyInformationFormValues>(() =>
    createPartyDrawerInitialValues(records),
  );
  const [syncedAddressSources, setSyncedAddressSources] = useState<Record<string, string>>({});
  const activeBranchId = useAppStore((state) => state.activeBranchId);
  const partyAccountOptions = usePartyManagementAccountOptions();
  const chartAccounts = useChartsOfAccounts();
  const termDropdown = useTermDropdownOptions();
  const transactionNumberSetup = useTransactionNumberSetupStore();
  const [errors, setErrors] = useState<PartyInformationFormErrors>({});
  const [isSaveDialogOpen, setIsSaveDialogOpen] = useState(false);
  const [isSaveConfirmPending, setIsSaveConfirmPending] = useState(false);
  const [accountTitleDialog, setAccountTitleDialog] =
    useState<ChartAccountQuickAddDialogState>(null);
  const [isTermDialogOpen, setIsTermDialogOpen] = useState(false);
  const activeAddress =
    values.addresses.find((address) => address.id === values.activeAddressId) ??
    values.addresses[0] ??
    values.address;
  const addressOptions = useAddressOptions({
    barangayCode: activeAddress.barangayCode,
    barangayName: activeAddress.barangay,
    cityMunicipalityCode: activeAddress.cityMunicipalityCode,
    cityMunicipalityName: activeAddress.cityMunicipality,
    provinceCode: activeAddress.provinceCode,
    provinceName: activeAddress.province,
    regionCode: activeAddress.regionCode,
    regionName: activeAddress.region,
  });
  const isClassificationSelected = Boolean(values.classification);
  const canSave = isClassificationSelected && values.partyTypes.length > 0;
  const partyNumberSetup = useMemo(
    () => getPartyManagementNumberSetup(transactionNumberSetup.setups, activeBranchId),
    [activeBranchId, transactionNumberSetup.setups],
  );
  const isAutoPartyCode = isPartyCodeAutoGenerated(partyNumberSetup);
  const partyCodePreview = getNextPartyCodePreview(partyNumberSetup);
  const accountingValues = useMemo(
    () =>
      applyPartyDefaultAccountingAccounts(
        values,
        values.partyTypes,
        partyAccountOptions.defaultAccounts,
      ),
    [partyAccountOptions.defaultAccounts, values],
  );
  const effectiveValues = useMemo(
    () =>
      isAutoPartyCode && partyCodePreview
        ? { ...accountingValues, partyCodeNo: partyCodePreview }
        : accountingValues,
    [accountingValues, isAutoPartyCode, partyCodePreview],
  );
  const atcDropdown = usePartyAtcCodeOptions(values.classification);
  const chartAccountById = useMemo(
    () => new Map(chartAccounts.flatAccounts.map(({ account }) => [account.id, account])),
    [chartAccounts.flatAccounts],
  );

  function updateField<TKey extends keyof PartyInformationFormValues>(
    field: TKey,
    value: PartyInformationFormValues[TKey],
  ) {
    setValues((current) => {
      if (field === "classification") {
        const classification = value as PartyInformationFormValues["classification"];
        const partyTypes = normalizePartyTypesForClassification(current.partyTypes, classification);
        const accountingAccounts = applyPartyDefaultAccountingAccounts(
          current,
          partyTypes,
          partyAccountOptions.defaultAccounts,
        );

        return {
          ...current,
          classification,
          partyTypes,
          partyName: "",
          tradeName: "",
          firstName: "",
          middleName: "",
          lastName: "",
          suffixName: "",
          honorific: "",
          gender: "",
          civilStatus: "",
          nationality: "",
          atcCode: "",
          addresses: clearAddressRolesForPartyTypes(current.addresses, partyTypes, classification),
          defaultReceivableAccount: accountingAccounts.defaultReceivableAccount,
          customerAdvanceAccount: accountingAccounts.customerAdvanceAccount,
          defaultPayableAccount: accountingAccounts.defaultPayableAccount,
          vendorAdvanceAccount: accountingAccounts.vendorAdvanceAccount,
          employeeAdvanceAccount: accountingAccounts.employeeAdvanceAccount,
          employeePayableAccount: accountingAccounts.employeePayableAccount,
        };
      }

      return {
        ...current,
        [field]: value,
      };
    });
    setErrors((current) => ({ ...current, [field]: undefined }));
  }

  function updateAddressField(field: keyof PartyAddress, value: string, addressId?: string) {
    if (!isClassificationSelected) {
      return;
    }

    setValues((current) => {
      const targetAddressId = addressId ?? current.activeAddressId;
      const addresses = current.addresses.map((address) =>
        address.id === targetAddressId ? { ...address, [field]: value } : address,
      );

      return {
        ...current,
        addresses: applySyncedAddressValues(addresses, syncedAddressSources),
      };
    });
    if (field === "addressLine1" || field === "addressLine2") {
      setErrors((current) => ({ ...current, [field]: undefined }));
    }
  }

  function handleInputChange(event: ChangeEvent<HTMLInputElement | HTMLSelectElement>) {
    const field = event.target.name as keyof PartyInformationFormValues;
    const value =
      field === "tin"
        ? FormatTinNumber(event.target.value)
        : field === "contactNo"
          ? FormatPhilippineContactNumber(event.target.value)
          : event.target.value;

    updateField(field, value as never);
  }

  function handleAddressInputChange(event: ChangeEvent<HTMLInputElement>) {
    updateAddressField(
      event.target.name as keyof PartyAddress,
      event.target.value,
      event.currentTarget.dataset.addressId,
    );
  }

  function copyAddress(sourceAddressId: string, targetAddressId: string) {
    if (!isClassificationSelected) {
      return;
    }

    if (!sourceAddressId) {
      setSyncedAddressSources((current) => removeSyncedAddressSource(current, targetAddressId));
      return;
    }

    if (sourceAddressId === targetAddressId) {
      return;
    }

    setSyncedAddressSources((current) =>
      createSyncedAddressSources(current, sourceAddressId, targetAddressId),
    );
    setValues((current) => {
      const nextSyncedAddressSources = createSyncedAddressSources(
        syncedAddressSources,
        sourceAddressId,
        targetAddressId,
      );

      return {
        ...current,
        addresses: applySyncedAddressValues(
          copyAddressValues(current.addresses, sourceAddressId, targetAddressId),
          nextSyncedAddressSources,
        ),
      };
    });
    clearAddressErrors([
      "addressLine1",
      "addressLine2",
      "regionCode",
      "provinceCode",
      "cityMunicipalityCode",
      "barangayCode",
    ]);
  }

  function handlePartyTypesChange(value: string | string[]) {
    if (!isClassificationSelected) {
      return;
    }

    const selectedValues = Array.isArray(value) ? value : [value];
    const partyTypes = selectedValues.filter(isKnownPartyType);

    setValues((current) => {
      const accountingAccounts = applyPartyDefaultAccountingAccounts(
        current,
        partyTypes,
        partyAccountOptions.defaultAccounts,
      );

      return {
        ...current,
        partyTypes,
        nationality:
          hasPersonalInformationPartyType(partyTypes) && !current.nationality
            ? PartyDefaultNationality
            : current.nationality,
        memberRegistrationDate: partyTypes.includes("Member")
          ? current.memberRegistrationDate || todayDateValue()
          : "",
        addresses: clearAddressRolesForPartyTypes(
          current.addresses,
          partyTypes,
          current.classification,
        ),
        defaultReceivableAccount: accountingAccounts.defaultReceivableAccount,
        customerAdvanceAccount: accountingAccounts.customerAdvanceAccount,
        defaultPayableAccount: accountingAccounts.defaultPayableAccount,
        vendorAdvanceAccount: accountingAccounts.vendorAdvanceAccount,
        employeeAdvanceAccount: accountingAccounts.employeeAdvanceAccount,
        employeePayableAccount: accountingAccounts.employeePayableAccount,
      };
    });
    setErrors((current) => ({ ...current, partyTypes: undefined }));
  }

  function selectAtcCode(value: string | string[]) {
    if (!isClassificationSelected) {
      return;
    }

    setValues((current) => ({
      ...current,
      atcCode: getSingleSelectedValue(value),
    }));
    setErrors((current) => ({ ...current, atcCode: undefined }));
  }

  function openAccountTitleDialog(field: PartyAccountingAccountField) {
    const selectedAccountId =
      values[field] || partyAccountOptions.accountOptions[field][0]?.id || "";
    const selectedAccount = chartAccountById.get(selectedAccountId);
    const parentAccount = selectedAccount?.parentId
      ? chartAccountById.get(selectedAccount.parentId)
      : null;

    if (!selectedAccount || !parentAccount) {
      toast.error("Select an account first.");
      return;
    }

    setAccountTitleDialog({ field, parentAccount });
  }

  function selectProvince(
    value: string | string[],
    addressId?: string,
    selectedOption?: PartyProvinceOption,
  ) {
    if (!isClassificationSelected) {
      return;
    }

    const code = getSingleSelectedValue(value);
    const option =
      selectedOption ?? addressOptions.provinceOptions.find((province) => province.value === code);

    setValues((current) => {
      const targetAddressId = addressId ?? current.activeAddressId;
      const addresses = current.addresses.map((address) =>
        address.id === targetAddressId
          ? {
              ...address,
              barangay: "",
              barangayCode: "",
              cityMunicipality: "",
              cityMunicipalityCode: "",
              province: option?.name ?? "",
              provinceCode: code,
              region: option?.regionName ?? "",
              regionCode: option?.regionCode ?? "",
            }
          : address,
      );

      return {
        ...current,
        addresses: applySyncedAddressValues(addresses, syncedAddressSources),
      };
    });
    clearAddressErrors(["regionCode", "provinceCode", "cityMunicipalityCode", "barangayCode"]);
  }

  function selectAutocompleteAddress(
    address: AddressAutocompleteItem,
    details?: AddressAutocompleteDetails,
    addressId?: string,
  ) {
    if (!isClassificationSelected) {
      return;
    }

    setValues((current) => {
      const targetAddressId = addressId ?? current.activeAddressId;
      const addresses = current.addresses.map((currentAddress) =>
        currentAddress.id === targetAddressId
          ? {
              ...currentAddress,
              addressLine1: details?.addressLine1 ?? currentAddress.addressLine1,
              addressLine2: details?.addressLine2 ?? currentAddress.addressLine2,
              barangay: address.barangay.name,
              barangayCode: address.barangay.code,
              cityMunicipality: address.cityMunicipality.name,
              cityMunicipalityCode: address.cityMunicipality.code,
              province: address.province.name,
              provinceCode: address.province.code,
              region: address.region.name,
              regionCode: address.region.code,
            }
          : currentAddress,
      );

      return {
        ...current,
        addresses: applySyncedAddressValues(addresses, syncedAddressSources),
      };
    });
    clearAddressErrors([
      "addressLine1",
      "addressLine2",
      "regionCode",
      "provinceCode",
      "cityMunicipalityCode",
      "barangayCode",
    ]);
  }

  function syncAutocompleteAddressDetails(details: AddressAutocompleteDetails, addressId?: string) {
    if (!isClassificationSelected) {
      return;
    }

    setValues((current) => {
      const targetAddressId = addressId ?? current.activeAddressId;
      const addresses = current.addresses.map((currentAddress) =>
        currentAddress.id === targetAddressId
          ? {
              ...currentAddress,
              addressLine1: details.addressLine1 ?? currentAddress.addressLine1,
              addressLine2: details.addressLine2 ?? currentAddress.addressLine2,
            }
          : currentAddress,
      );

      return {
        ...current,
        addresses: applySyncedAddressValues(addresses, syncedAddressSources),
      };
    });
    clearAddressErrors(["addressLine1", "addressLine2"]);
  }

  function selectCityMunicipality(
    value: string | string[],
    addressId?: string,
    selectedOption?: AppAdvancedDropdownOption,
  ) {
    if (!isClassificationSelected) {
      return;
    }

    const code = getSingleSelectedValue(value);
    const option =
      selectedOption ??
      addressOptions.cityMunicipalityOptions.find(
        (cityMunicipality) => cityMunicipality.value === code,
      );

    setValues((current) => {
      const targetAddressId = addressId ?? current.activeAddressId;
      const addresses = current.addresses.map((address) =>
        address.id === targetAddressId
          ? {
              ...address,
              barangay: "",
              barangayCode: "",
              cityMunicipality: option?.name ?? "",
              cityMunicipalityCode: code,
            }
          : address,
      );

      return {
        ...current,
        addresses: applySyncedAddressValues(addresses, syncedAddressSources),
      };
    });
    clearAddressErrors(["cityMunicipalityCode", "barangayCode"]);
  }

  function selectBarangay(
    value: string | string[],
    addressId?: string,
    selectedOption?: AppAdvancedDropdownOption,
  ) {
    if (!isClassificationSelected) {
      return;
    }

    const code = getSingleSelectedValue(value);
    const option =
      selectedOption ?? addressOptions.barangayOptions.find((barangay) => barangay.value === code);

    setValues((current) => {
      const targetAddressId = addressId ?? current.activeAddressId;
      const addresses = current.addresses.map((address) =>
        address.id === targetAddressId
          ? {
              ...address,
              barangay: option?.name ?? "",
              barangayCode: code,
            }
          : address,
      );

      return {
        ...current,
        addresses: applySyncedAddressValues(addresses, syncedAddressSources),
      };
    });
    clearAddressErrors(["barangayCode"]);
  }

  function clearAddressErrors(fields: (keyof PartyInformationFormErrors)[]) {
    setErrors((current) => {
      const nextErrors = { ...current };

      for (const field of fields) {
        nextErrors[field] = undefined;
      }

      return nextErrors;
    });
  }

  function selectTerm(value: string | string[]) {
    const termId = getSingleSelectedValue(value);
    const term = termDropdown.terms.find((currentTerm) => currentTerm.id === termId);

    updateTermSelection(termId, term?.name ?? "");
  }

  function updateTermSelection(termId: string, termName: string) {
    setValues((current) => ({
      ...current,
      termId,
      termName,
    }));
  }

  function validateBeforeSubmit() {
    const nextErrors = validatePartyInformationForm(effectiveValues);

    if (Object.keys(nextErrors).length > 0) {
      setErrors(nextErrors);
      toast.error(PartyInformationRequiredFieldsToastMessage);
      return false;
    }

    return true;
  }

  function handleSubmit(event?: FormEvent<HTMLFormElement>) {
    event?.preventDefault();

    if (!validateBeforeSubmit()) {
      return;
    }

    const record = createPartyInformationRecord(effectiveValues);

    onAddRecord(record);
    onCreateParty(record);
    onClose();
  }

  return (
    <ModuleDrawer
      description={description}
      footer={
        <div className="flex flex-wrap justify-end gap-2">
          <button
            type="button"
            onClick={onClose}
            className={PartyManagementDrawerSecondaryActionClassName}
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={() => {
              if (validateBeforeSubmit()) {
                setIsSaveDialogOpen(true);
              }
            }}
            disabled={isPending || !canSave}
            className={PartyManagementDrawerPrimaryActionClassName}
          >
            Save Party
          </button>
        </div>
      }
      isOpen={isOpen}
      maxWidthClassName="max-w-5xl"
      onClose={onClose}
      title={title}
    >
      <AppDialog
        confirmLabel="Confirm"
        description="This will create a new party using the details you entered."
        iconTone="question"
        isOpen={isSaveDialogOpen}
        isPending={isPending || isSaveConfirmPending}
        pendingLabel={ModuleSavingLabel}
        title="Save this party?"
        tone="success"
        onCancel={() => {
          if (!isPending && !isSaveConfirmPending) {
            setIsSaveDialogOpen(false);
          }
        }}
        onConfirm={() => {
          setIsSaveConfirmPending(true);
          handleSubmit();
          window.setTimeout(() => {
            setIsSaveConfirmPending(false);
            setIsSaveDialogOpen(false);
          }, 700);
        }}
      />
      <div id={PartyManagementDrawerFormId} className="px-6 py-5">
        <PartyInformationDetailsFields
          accountOptions={partyAccountOptions.accountOptions}
          atcOptions={atcDropdown.options}
          errors={errors}
          isClassificationSelected={isClassificationSelected}
          isPartyCodeReadonly={isAutoPartyCode}
          isReadonly={false}
          partyTypeOptions={PartyTypeOptions}
          termOptions={termDropdown.options}
          values={effectiveValues}
          syncedAddressSources={syncedAddressSources}
          canAddAccountTitle={chartAccounts.permissions.canCreate}
          canAddTerm={termDropdown.permissions.canCreate}
          onAddAccountTitle={openAccountTitleDialog}
          onAddTerm={() => setIsTermDialogOpen(true)}
          onAddressInputChange={handleAddressInputChange}
          onCopyAddress={copyAddress}
          onInputChange={handleInputChange}
          onPartyTypesChange={handlePartyTypesChange}
          onSelectBarangay={selectBarangay}
          onSelectAtcCode={selectAtcCode}
          onSelectAutocompleteAddress={selectAutocompleteAddress}
          onSyncAutocompleteAddressDetails={syncAutocompleteAddressDetails}
          onSelectCityMunicipality={selectCityMunicipality}
          onSelectProvince={selectProvince}
          onSelectTerm={selectTerm}
          onUpdateField={updateField}
        />
      </div>
      <ChartAccountQuickAddDialog
        accountLabel={
          accountTitleDialog
            ? PartyAccountingAccountFieldLabels[accountTitleDialog.field]
            : "Account"
        }
        isOpen={Boolean(accountTitleDialog)}
        parentAccount={accountTitleDialog?.parentAccount ?? null}
        onClose={() => setAccountTitleDialog(null)}
        onSaved={(accountId) => {
          if (accountTitleDialog) {
            updateField(accountTitleDialog.field, accountId);
          }
          chartAccounts.refreshAccounts();
          void partyAccountOptions.refetch();
          setAccountTitleDialog(null);
        }}
      />
      <TermManagementQuickAddDialog
        isOpen={isTermDialogOpen}
        onClose={() => setIsTermDialogOpen(false)}
        onSaved={(term) => {
          updateTermSelection(term.id, term.name);
          void termDropdown.refetch();
          setIsTermDialogOpen(false);
        }}
      />
    </ModuleDrawer>
  );
}

type ChartAccountQuickAddDialogState = {
  field: PartyAccountingAccountField;
  parentAccount: ChartAccount;
} | null;

function createPartyDrawerInitialValues(
  records: PartyInformationRecord[],
): PartyInformationFormValues {
  return {
    ...PartyInformationInitialFormValues,
    partyCodeNo: createNextPartyCode(records),
    status: "Active",
  };
}

function createNextPartyCode(records: PartyInformationRecord[]) {
  const nextNumber =
    records.reduce((highest, record) => {
      const match = record.partyCodeNo.match(/(\d+)$/);
      const number = match ? Number.parseInt(match[1], 10) : Number.NaN;

      return Number.isFinite(number) ? Math.max(highest, number) : highest;
    }, 0) + 1;

  return `PTY-${nextNumber.toString().padStart(4, "0")}`;
}

function copyAddressValues(
  addresses: PartyAddress[],
  sourceAddressId: string,
  targetAddressId: string,
) {
  const sourceAddress = addresses.find((address) => address.id === sourceAddressId);

  if (!sourceAddress) {
    return addresses;
  }

  return addresses.map((address) => {
    if (address.id !== targetAddressId) {
      return address;
    }

    return {
      ...address,
      addressLine1: sourceAddress.addressLine1,
      addressLine2: sourceAddress.addressLine2,
      barangay: sourceAddress.barangay,
      barangayCode: sourceAddress.barangayCode,
      cityMunicipality: sourceAddress.cityMunicipality,
      cityMunicipalityCode: sourceAddress.cityMunicipalityCode,
      isForeign: sourceAddress.isForeign,
      province: sourceAddress.province,
      provinceCode: sourceAddress.provinceCode,
      region: sourceAddress.region,
      regionCode: sourceAddress.regionCode,
    };
  });
}

function createSyncedAddressSources(
  current: Record<string, string>,
  sourceAddressId: string,
  targetAddressId: string,
) {
  return Object.fromEntries(
    Object.entries({
      ...current,
      [targetAddressId]: sourceAddressId,
    }).filter(
      ([targetId, sourceId]) => targetId !== sourceAddressId && sourceId !== targetAddressId,
    ),
  );
}

function removeSyncedAddressSource(current: Record<string, string>, targetAddressId: string) {
  return Object.fromEntries(
    Object.entries(current).filter(([addressId]) => addressId !== targetAddressId),
  );
}

function applySyncedAddressValues(
  addresses: PartyAddress[],
  syncedAddressSources: Record<string, string>,
) {
  return Object.entries(syncedAddressSources).reduce(
    (currentAddresses, [targetAddressId, sourceAddressId]) =>
      copyAddressValues(currentAddresses, sourceAddressId, targetAddressId),
    addresses,
  );
}

function getSingleSelectedValue(value: string | string[]) {
  return Array.isArray(value) ? (value[0] ?? "") : value;
}
