export const GlobalReferenceModuleOptions = [
  "",
  "Official Receipt",
  "Collection Receipt",
  "Acknowledgement Receipt",
  "Provisional Receipt",
  "Bank Reconciliation",
  "PDC Warehouse",
  "Disbursement Voucher",
  "Cash Advance",
  "Cash Advance Multiple Entry",
  "Petty Cash Voucher",
  "Petty Cash Fund",
  "Petty Cash Fund Replenishment",
  "Petty Cash Advance Replenishment",
  "Petty Cash Advance",
  "Request For Payment",
  "Advances To Supplier",
  "Accounts Payable Voucher",
  "Journal Voucher",
  "Debit Memo",
  "Credit Memo",
  "Sales Quotation",
  "Sales Order",
  "Sales Invoice",
  "Billing",
  "Billing Statement",
  "Billing Invoice",
  "Service Invoice",
  "Cash Sales Invoice",
  "Sales Journal",
  "Statement of Account",
  "Receiving Report",
  "Goods Receipt",
  "Inventory Account",
  "Material Request",
  "Pick List",
  "Goods Issue",
  "Delivery Receipt",
  "Purchase Request",
  "Canvass Form",
  "Purchase Order",
  "Purchase Journal",
  "Fixed Asset",
  "Others",
] as const;
