import { formatTransactionNumber } from "@/app/src/services/modules/system-administration/transaction-number-setup/TransactionNumberGenerationService";
import type { TransactionNumberSetupRecord } from "@/app/src/types/modules/system-administration/transaction-number-setup/TransactionNumberSetupTypes";

const WarehouseModuleCode = "WM";

export function getWarehouseNumberSetup(setups: TransactionNumberSetupRecord[], branchUnitId?: number | null) {
  return setups.find(
    (setup) =>
      setup.moduleCode === WarehouseModuleCode &&
      setup.status === "Active" &&
      (setup.scope !== "branch" || !branchUnitId || setup.branchIds.includes(String(branchUnitId))),
  );
}

export function isWarehouseCodeAutoGenerated(setup: TransactionNumberSetupRecord | undefined) {
  return setup?.inputMode === "Auto";
}

export function getNextWarehouseCodePreview(setup: TransactionNumberSetupRecord | undefined) {
  return setup && isWarehouseCodeAutoGenerated(setup) ? formatTransactionNumber(setup) : "";
}
