"use client";

import { useMemo, useState, type ChangeEvent, type FormEvent } from "react";
import toast from "react-hot-toast";
import { useParams, usePathname, useRouter, useSearchParams } from "next/navigation";
import {
  PartyManagementEditFromParam,
  PartyManagementEditFromViewQuery,
  PartyManagementEditFromViewValue,
  PartyManagementHref,
  PartyDefaultNationality,
  PartyTypeOptions,
} from "@/app/src/constants/modules/party-management/PartyManagementConstants";
import { FormatPhilippineContactNumber } from "@/app/src/data/shared/contact/ContactData";
import { FormatTinNumber } from "@/app/src/data/shared/tax/TaxData";
import {
  PartyInformationInitialFormValues,
  applyPartyDefaultAccountingAccounts,
  clearAddressRolesForPartyTypes,
  createPartyInformationFormValues,
  createPartyInformationRecord,
  hasPersonalInformationPartyType,
  isPartyEntityTypeWithholdingDefaultEnabled,
  isKnownPartyType,
  normalizePartyEntityTypeForClassification,
  normalizePartyTypesForClassification,
  updatePartyInformationRecord,
} from "@/app/src/data/modules/party-management/PartyManagementData";
import { useTermDropdownOptions } from "@/app/src/hooks/modules/financial-maintenance/terms-maintenance/useTermDropdownOptions";
import { usePartyManagementAccountOptions } from "@/app/src/hooks/modules/party-management/usePartyManagementAccountOptions";
import { usePartyTaxDefaultOptions } from "@/app/src/hooks/shared/tax/useTaxOptions";
import { useAddressOptions } from "@/app/src/hooks/shared/address/useAddressOptions";
import type {
  PartyAddress,
  PartyInformationActionMode,
  PartyInformationFormErrors,
  PartyInformationFormValues,
  PartyInformationStatus,
  PartyProvinceOption,
} from "@/app/src/types/modules/party-management/PartyManagementTypes";
import {
  PartyInformationRequiredFieldsToastMessage,
  validatePartyInformationForm,
} from "@/app/src/validations/modules/party-management/PartyManagementValidation";
import { usePartyManagementStore } from "@/app/src/hooks/modules/party-management/usePartyManagement";
import { useAppStore } from "@/app/src/hooks/shared/app/useAppStore";
import { useTransactionNumberSetupStore } from "@/app/src/hooks/modules/system-administration/transaction-number-setup/useTransactionNumberSetup";
import {
  getNextPartyCodePreview,
  getPartyManagementNumberSetup,
  isPartyCodeAutoGenerated,
} from "@/app/src/services/modules/party-management/PartyManagementNumbering";
import type {
  AddressAutocompleteDetails,
  AddressAutocompleteItem,
} from "@/app/src/types/shared/address/AddressTypes";
import type { AppAdvancedDropdownOption } from "@/app/src/ui/shared/advanced-dropdown/AppAdvancedDropdown";
import { todayDateValue } from "@/app/src/utils/date.util";

export function usePartyManagementAction() {
  const router = useRouter();
  const pathname = usePathname();
  const params = useParams<{ recordId?: string }>();
  const searchParams = useSearchParams();
  const activeBranchId = useAppStore((state) => state.activeBranchId);
  const partyManagement = usePartyManagementStore();
  const partyAccountOptions = usePartyManagementAccountOptions();
  const transactionNumberSetup = useTransactionNumberSetupStore();
  const termDropdown = useTermDropdownOptions();
  const mode = getActionMode(pathname);
  const openedFromView =
    mode === "edit" &&
    searchParams.get(PartyManagementEditFromParam) === PartyManagementEditFromViewValue;
  const existingRecord = partyManagement.records.find((record) => record.id === params.recordId);
  const [values, setValues] = useState<PartyInformationFormValues>(() =>
    existingRecord
      ? createPartyInformationFormValues(existingRecord)
      : PartyInformationInitialFormValues,
  );
  const [syncedAddressSources, setSyncedAddressSources] = useState<Record<string, string>>({});
  const [errors, setErrors] = useState<PartyInformationFormErrors>({});
  const [isStatusDialogOpen, setIsStatusDialogOpen] = useState(false);
  const activeAddress =
    values.addresses.find((address) => address.id === values.activeAddressId) ??
    values.addresses[0] ??
    values.address;
  const addressOptions = useAddressOptions({
    barangayCode: activeAddress.barangayCode,
    barangayName: activeAddress.barangay,
    cityMunicipalityCode: activeAddress.cityMunicipalityCode,
    cityMunicipalityName: activeAddress.cityMunicipality,
    provinceCode: activeAddress.provinceCode,
    provinceName: activeAddress.province,
    regionCode: activeAddress.regionCode,
    regionName: activeAddress.region,
  });
  const isReadonly = mode === "view";
  const partyNumberSetup = useMemo(
    () => getPartyManagementNumberSetup(transactionNumberSetup.setups, activeBranchId),
    [activeBranchId, transactionNumberSetup.setups],
  );
  const isAutoPartyCode = mode === "add" && isPartyCodeAutoGenerated(partyNumberSetup);
  const partyCodePreview = getNextPartyCodePreview(partyNumberSetup);
  const accountingValues = useMemo(
    () =>
      applyPartyDefaultAccountingAccounts(
        values,
        values.partyTypes,
        partyAccountOptions.defaultAccounts,
      ),
    [partyAccountOptions.defaultAccounts, values],
  );
  const effectiveValues = useMemo(
    () =>
      isAutoPartyCode && partyCodePreview
        ? { ...accountingValues, partyCodeNo: partyCodePreview }
        : accountingValues,
    [accountingValues, isAutoPartyCode, partyCodePreview],
  );
  const isClassificationSelected = Boolean(values.classification);
  const canSave = isClassificationSelected && values.partyTypes.length > 0;
  const nextStatus: PartyInformationStatus =
    existingRecord?.status === "Active" ? "Inactive" : "Active";
  const taxDefaults = usePartyTaxDefaultOptions();
  const viewHref = existingRecord
    ? `${PartyManagementHref}/view/${existingRecord.id}`
    : PartyManagementHref;
  const cancelHref = mode === "edit" && openedFromView ? viewHref : PartyManagementHref;
  const editHref = existingRecord
    ? `${PartyManagementHref}/edit/${existingRecord.id}?${PartyManagementEditFromViewQuery}`
    : undefined;

  function updateField<TKey extends keyof PartyInformationFormValues>(
    field: TKey,
    value: PartyInformationFormValues[TKey],
  ) {
    if (isReadonly) {
      return;
    }

    setValues((current) => {
      if (field === "classification") {
        const classification = value as PartyInformationFormValues["classification"];
        const partyTypes = normalizePartyTypesForClassification(current.partyTypes, classification);
        const accountingAccounts = applyPartyDefaultAccountingAccounts(
          current,
          partyTypes,
          partyAccountOptions.defaultAccounts,
        );

        return {
          ...current,
          classification,
          partyEntityType: "",
          partyTypes,
          partyName: "",
          tradeName: "",
          firstName: "",
          middleName: "",
          lastName: "",
          suffixName: "",
          honorific: "",
          gender: "",
          civilStatus: "",
          nationality: "",
          atcCode: "",
          defaultPurchaseInputVatTaxSourceKey: "",
          defaultPurchaseEwtTaxSourceKey: "",
          defaultPurchaseFwtTaxSourceKey: "",
          defaultPurchaseWvatTaxSourceKey: "",
          defaultSalesOutputVatTaxSourceKey: "",
          defaultSalesCwtTaxSourceKey: "",
          defaultSalesWvatTaxSourceKey: "",
          addresses: clearAddressRolesForPartyTypes(current.addresses, partyTypes, classification),
          defaultReceivableAccount: accountingAccounts.defaultReceivableAccount,
          customerAdvanceAccount: accountingAccounts.customerAdvanceAccount,
          defaultPayableAccount: accountingAccounts.defaultPayableAccount,
          vendorAdvanceAccount: accountingAccounts.vendorAdvanceAccount,
          employeeAdvanceAccount: accountingAccounts.employeeAdvanceAccount,
          employeePayableAccount: accountingAccounts.employeePayableAccount,
        };
      }

      return {
        ...current,
        [field]: value,
        ...(field === "partyEntityType" &&
        !isPartyEntityTypeWithholdingDefaultEnabled(
          value as PartyInformationFormValues["partyEntityType"],
        )
          ? {
              defaultPurchaseFwtTaxSourceKey: "",
              defaultPurchaseWvatTaxSourceKey: "",
              defaultSalesWvatTaxSourceKey: "",
            }
          : {}),
      };
    });
    setErrors((current) => ({ ...current, [field]: undefined }));
  }

  function updateAddressField(field: keyof PartyAddress, value: string, addressId?: string) {
    if (isReadonly || !isClassificationSelected) {
      return;
    }

    setValues((current) => {
      const targetAddressId = addressId ?? current.activeAddressId;
      const addresses = current.addresses.map((address) =>
        address.id === targetAddressId ? { ...address, [field]: value } : address,
      );

      return {
        ...current,
        addresses: applySyncedAddressValues(addresses, syncedAddressSources),
      };
    });
    if (field === "addressLine1" || field === "addressLine2") {
      setErrors((current) => ({ ...current, [field]: undefined }));
    }
  }

  function handleInputChange(event: ChangeEvent<HTMLInputElement | HTMLSelectElement>) {
    const field = event.target.name as keyof PartyInformationFormValues;
    const value =
      field === "tin"
        ? FormatTinNumber(event.target.value)
        : field === "contactNo"
          ? FormatPhilippineContactNumber(event.target.value)
          : event.target.value;

    updateField(field, value as never);
  }

  function handleAddressInputChange(event: ChangeEvent<HTMLInputElement>) {
    updateAddressField(
      event.target.name as keyof PartyAddress,
      event.target.value,
      event.currentTarget.dataset.addressId,
    );
  }

  function copyAddress(sourceAddressId: string, targetAddressId: string) {
    if (isReadonly || !isClassificationSelected) {
      return;
    }

    if (!sourceAddressId) {
      setSyncedAddressSources((current) => removeSyncedAddressSource(current, targetAddressId));
      return;
    }

    if (sourceAddressId === targetAddressId) {
      return;
    }

    setSyncedAddressSources((current) =>
      createSyncedAddressSources(current, sourceAddressId, targetAddressId),
    );
    setValues((current) => {
      const nextSyncedAddressSources = createSyncedAddressSources(
        syncedAddressSources,
        sourceAddressId,
        targetAddressId,
      );

      return {
        ...current,
        addresses: applySyncedAddressValues(
          copyAddressValues(current.addresses, sourceAddressId, targetAddressId),
          nextSyncedAddressSources,
        ),
      };
    });
    setErrors((current) => ({
      ...current,
      addressLine1: undefined,
      addressLine2: undefined,
      barangayCode: undefined,
      cityMunicipalityCode: undefined,
      provinceCode: undefined,
      regionCode: undefined,
    }));
  }

  function handlePartyTypesChange(value: string | string[]) {
    if (isReadonly || !isClassificationSelected) {
      return;
    }

    const values = Array.isArray(value) ? value : [value];
    const partyTypes = values.filter(isKnownPartyType);

    setValues((current) => {
      const accountingAccounts = applyPartyDefaultAccountingAccounts(
        current,
        partyTypes,
        partyAccountOptions.defaultAccounts,
      );

      return {
        ...current,
        partyTypes,
        ...(current.classification === "Individual"
          ? {
              defaultPurchaseFwtTaxSourceKey: "",
              defaultPurchaseWvatTaxSourceKey: "",
              defaultSalesWvatTaxSourceKey: "",
            }
          : {}),
        partyEntityType: normalizePartyEntityTypeForClassification(
          current.partyEntityType,
          current.classification,
        ),
        nationality:
          hasPersonalInformationPartyType(partyTypes) && !current.nationality
            ? PartyDefaultNationality
            : current.nationality,
        memberRegistrationDate: partyTypes.includes("Member")
          ? current.memberRegistrationDate || todayDateValue()
          : "",
        addresses: clearAddressRolesForPartyTypes(
          current.addresses,
          partyTypes,
          current.classification,
        ),
        defaultReceivableAccount: accountingAccounts.defaultReceivableAccount,
        customerAdvanceAccount: accountingAccounts.customerAdvanceAccount,
        defaultPayableAccount: accountingAccounts.defaultPayableAccount,
        vendorAdvanceAccount: accountingAccounts.vendorAdvanceAccount,
        employeeAdvanceAccount: accountingAccounts.employeeAdvanceAccount,
        employeePayableAccount: accountingAccounts.employeePayableAccount,
      };
    });
    setErrors((current) => ({ ...current, partyTypes: undefined }));
  }

  function selectRegion(value: string | string[]) {
    if (isReadonly || !isClassificationSelected) {
      return;
    }

    const code = getSingleSelectedValue(value);
    const option = addressOptions.regionOptions.find((region) => region.value === code);

    setValues((current) => {
      const addresses = current.addresses.map((address) =>
        address.id === current.activeAddressId
          ? {
              ...address,
              barangay: "",
              barangayCode: "",
              cityMunicipality: "",
              cityMunicipalityCode: "",
              province: "",
              provinceCode: "",
              region: option?.name ?? "",
              regionCode: code,
            }
          : address,
      );

      return {
        ...current,
        addresses: applySyncedAddressValues(addresses, syncedAddressSources),
      };
    });
    setErrors((current) => ({
      ...current,
      barangayCode: undefined,
      cityMunicipalityCode: undefined,
      provinceCode: undefined,
      regionCode: undefined,
    }));
  }

  function selectProvince(
    value: string | string[],
    addressId?: string,
    selectedOption?: PartyProvinceOption,
  ) {
    if (isReadonly || !isClassificationSelected) {
      return;
    }

    const code = getSingleSelectedValue(value);
    const option =
      selectedOption ?? addressOptions.provinceOptions.find((province) => province.value === code);

    setValues((current) => {
      const targetAddressId = addressId ?? current.activeAddressId;
      const addresses = current.addresses.map((address) =>
        address.id === targetAddressId
          ? {
              ...address,
              barangay: "",
              barangayCode: "",
              cityMunicipality: "",
              cityMunicipalityCode: "",
              province: option?.name ?? "",
              provinceCode: code,
              region: option?.regionName ?? "",
              regionCode: option?.regionCode ?? "",
            }
          : address,
      );

      return {
        ...current,
        addresses: applySyncedAddressValues(addresses, syncedAddressSources),
      };
    });
    setErrors((current) => ({
      ...current,
      addressLine1: undefined,
      addressLine2: undefined,
      barangayCode: undefined,
      cityMunicipalityCode: undefined,
      provinceCode: undefined,
      regionCode: undefined,
    }));
  }

  function selectAutocompleteAddress(
    address: AddressAutocompleteItem,
    details?: AddressAutocompleteDetails,
    addressId?: string,
  ) {
    if (isReadonly || !isClassificationSelected) {
      return;
    }

    setValues((current) => {
      const targetAddressId = addressId ?? current.activeAddressId;
      const addresses = current.addresses.map((currentAddress) =>
        currentAddress.id === targetAddressId
          ? {
              ...currentAddress,
              addressLine1: details?.addressLine1 ?? currentAddress.addressLine1,
              addressLine2: details?.addressLine2 ?? currentAddress.addressLine2,
              barangay: address.barangay.name,
              barangayCode: address.barangay.code,
              cityMunicipality: address.cityMunicipality.name,
              cityMunicipalityCode: address.cityMunicipality.code,
              province: address.province.name,
              provinceCode: address.province.code,
              region: address.region.name,
              regionCode: address.region.code,
            }
          : currentAddress,
      );

      return {
        ...current,
        addresses: applySyncedAddressValues(addresses, syncedAddressSources),
      };
    });
    setErrors((current) => ({
      ...current,
      barangayCode: undefined,
      cityMunicipalityCode: undefined,
      provinceCode: undefined,
      regionCode: undefined,
    }));
  }

  function syncAutocompleteAddressDetails(details: AddressAutocompleteDetails, addressId?: string) {
    if (isReadonly || !isClassificationSelected) {
      return;
    }

    setValues((current) => {
      const targetAddressId = addressId ?? current.activeAddressId;
      const addresses = current.addresses.map((currentAddress) =>
        currentAddress.id === targetAddressId
          ? {
              ...currentAddress,
              addressLine1: details.addressLine1 ?? currentAddress.addressLine1,
              addressLine2: details.addressLine2 ?? currentAddress.addressLine2,
            }
          : currentAddress,
      );

      return {
        ...current,
        addresses: applySyncedAddressValues(addresses, syncedAddressSources),
      };
    });
    setErrors((current) => ({
      ...current,
      addressLine1: undefined,
      addressLine2: undefined,
    }));
  }

  function selectCityMunicipality(
    value: string | string[],
    addressId?: string,
    selectedOption?: AppAdvancedDropdownOption,
  ) {
    if (isReadonly || !isClassificationSelected) {
      return;
    }

    const code = getSingleSelectedValue(value);
    const option =
      selectedOption ??
      addressOptions.cityMunicipalityOptions.find(
        (cityMunicipality) => cityMunicipality.value === code,
      );

    setValues((current) => {
      const targetAddressId = addressId ?? current.activeAddressId;
      const addresses = current.addresses.map((address) =>
        address.id === targetAddressId
          ? {
              ...address,
              barangay: "",
              barangayCode: "",
              cityMunicipality: option?.name ?? "",
              cityMunicipalityCode: code,
            }
          : address,
      );

      return {
        ...current,
        addresses: applySyncedAddressValues(addresses, syncedAddressSources),
      };
    });
    setErrors((current) => ({
      ...current,
      barangayCode: undefined,
      cityMunicipalityCode: undefined,
    }));
  }

  function selectBarangay(
    value: string | string[],
    addressId?: string,
    selectedOption?: AppAdvancedDropdownOption,
  ) {
    if (isReadonly || !isClassificationSelected) {
      return;
    }

    const code = getSingleSelectedValue(value);
    const option =
      selectedOption ?? addressOptions.barangayOptions.find((barangay) => barangay.value === code);

    setValues((current) => {
      const targetAddressId = addressId ?? current.activeAddressId;
      const addresses = current.addresses.map((address) =>
        address.id === targetAddressId
          ? {
              ...address,
              barangay: option?.name ?? "",
              barangayCode: code,
            }
          : address,
      );

      return {
        ...current,
        addresses: applySyncedAddressValues(addresses, syncedAddressSources),
      };
    });
    setErrors((current) => ({ ...current, barangayCode: undefined }));
  }

  function validateBeforeSubmit() {
    const nextErrors = validatePartyInformationForm(effectiveValues);

    if (Object.keys(nextErrors).length > 0) {
      setErrors(nextErrors);
      toast.error(PartyInformationRequiredFieldsToastMessage);
      return false;
    }

    return true;
  }

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (!validateBeforeSubmit()) {
      return;
    }

    if (mode === "edit" && existingRecord) {
      partyManagement.updateRecord(updatePartyInformationRecord(existingRecord, effectiveValues));
    } else {
      partyManagement.addRecord(createPartyInformationRecord(effectiveValues));
    }

    router.push(mode === "edit" && openedFromView ? viewHref : PartyManagementHref);
  }

  function updateAddressMeta(
    addressId: string,
    field: "addressName" | "isBilling" | "isDelivery" | "isForeign" | "isHome",
    value: string | boolean,
  ) {
    if (isReadonly) {
      return;
    }

    setValues((current) => ({
      ...current,
      addresses: current.addresses.map((address) =>
        updateAddressRole(address, addressId, field, value),
      ),
    }));
  }

  function selectTerm(value: string | string[]) {
    const termId = getSingleSelectedValue(value);
    const term = termDropdown.terms.find((currentTerm) => currentTerm.id === termId);

    updateTermSelection(termId, term?.name ?? "");
    setErrors((current) => ({ ...current, termId: undefined }));
  }

  function updateTermSelection(termId: string, termName: string) {
    setValues((current) => ({
      ...current,
      termId,
      termName,
    }));
  }

  function handleConfirmStatusChange() {
    if (!existingRecord) {
      return;
    }

    partyManagement.updateRecord({
      ...existingRecord,
      status: nextStatus,
      updatedAt: new Date().toISOString(),
    });
    setValues((current) => ({ ...current, status: nextStatus }));
    setIsStatusDialogOpen(false);
  }

  return {
    addressOptions,
    accountOptions: partyAccountOptions.accountOptions,
    accountOptionsRefetch: partyAccountOptions.refetch,
    cancelHref,
    editHref,
    errors,
    existingRecord,
    handleAddressInputChange,
    handleConfirmStatusChange,
    handleInputChange,
    handlePartyTypesChange,
    handleSubmit,
    isClassificationSelected,
    canSave,
    isMutating: partyManagement.isMutating,
    isPartyCodeReadonly: isAutoPartyCode,
    isReadonly,
    isStatusDialogOpen,
    mode,
    needsRecord: mode === "edit" || mode === "view",
    nextStatus,
    partyTypeOptions: PartyTypeOptions,
    taxDefaultOptionsError: taxDefaults.isError,
    taxDefaultOptionsLoading: taxDefaults.isLoading,
    taxDefaultOptions: taxDefaults.options,
    refreshTermOptions: termDropdown.refetch,
    copyAddress,
    selectBarangay,
    selectAutocompleteAddress,
    syncAutocompleteAddressDetails,
    selectCityMunicipality,
    selectProvince,
    selectRegion,
    selectTerm,
    setSelectedTerm: updateTermSelection,
    setIsStatusDialogOpen,
    syncedAddressSources,
    termOptions: termDropdown.options,
    termPermissions: termDropdown.permissions,
    updateAddressMeta,
    updateField,
    validateBeforeSubmit,
    values: effectiveValues,
  };
}

function updateAddressRole(
  address: PartyAddress,
  addressId: string,
  field: "addressName" | "isBilling" | "isDelivery" | "isForeign" | "isHome",
  value: string | boolean,
) {
  if (address.id !== addressId) {
    return address;
  }

  return {
    ...address,
    [field]: value,
  };
}

function copyAddressValues(
  addresses: PartyAddress[],
  sourceAddressId: string,
  targetAddressId: string,
) {
  const sourceAddress = addresses.find((address) => address.id === sourceAddressId);

  if (!sourceAddress) {
    return addresses;
  }

  return addresses.map((address) => {
    if (address.id !== targetAddressId) {
      return address;
    }

    return {
      ...address,
      addressLine1: sourceAddress.addressLine1,
      addressLine2: sourceAddress.addressLine2,
      barangay: sourceAddress.barangay,
      barangayCode: sourceAddress.barangayCode,
      cityMunicipality: sourceAddress.cityMunicipality,
      cityMunicipalityCode: sourceAddress.cityMunicipalityCode,
      isForeign: sourceAddress.isForeign,
      province: sourceAddress.province,
      provinceCode: sourceAddress.provinceCode,
      region: sourceAddress.region,
      regionCode: sourceAddress.regionCode,
    };
  });
}

function createSyncedAddressSources(
  current: Record<string, string>,
  sourceAddressId: string,
  targetAddressId: string,
) {
  return Object.fromEntries(
    Object.entries({
      ...current,
      [targetAddressId]: sourceAddressId,
    }).filter(
      ([targetId, sourceId]) => targetId !== sourceAddressId && sourceId !== targetAddressId,
    ),
  );
}

function removeSyncedAddressSource(current: Record<string, string>, targetAddressId: string) {
  return Object.fromEntries(
    Object.entries(current).filter(([addressId]) => addressId !== targetAddressId),
  );
}

function applySyncedAddressValues(
  addresses: PartyAddress[],
  syncedAddressSources: Record<string, string>,
) {
  return Object.entries(syncedAddressSources).reduce(
    (currentAddresses, [targetAddressId, sourceAddressId]) =>
      copyAddressValues(currentAddresses, sourceAddressId, targetAddressId),
    addresses,
  );
}

function getActionMode(pathname: string): PartyInformationActionMode {
  if (pathname.includes("/view/")) {
    return "view";
  }

  if (pathname.includes("/edit/")) {
    return "edit";
  }

  return "add";
}

function getSingleSelectedValue(value: string | string[]) {
  return Array.isArray(value) ? (value[0] ?? "") : value;
}
